name: Build ESP-AT Project

on: push

jobs:
  build-esp32-wroom-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROOM-32
      artifacts_name: esp32-wroom-at
    secrets: inherit

  build-esp32-wrover-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROVER-32
      artifacts_name: esp32-wrover-at
    secrets: inherit

  build-esp32-pico-d4-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: PICO-D4
      artifacts_name: esp32-pico-d4-at
    secrets: inherit

  build-esp32-solo-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: SOLO-1
      artifacts_name: esp32-solo-1-at
    secrets: inherit

  build-esp32-d2wd-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: ESP32-D2WD
      artifacts_name: esp32-d2wd-at
    secrets: inherit

  build-esp32-mini-1-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: MINI-1
      artifacts_name: esp32-mini-1-at
    secrets: inherit

  build-esp32-sdio-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: ESP32-SDIO
      artifacts_name: esp32-sdio-at
    secrets: inherit

  build-esp32-at-all-function-test-without-bt:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROVER-32
      artifacts_name: esp32-at-all-function-test-without-bt
    secrets: inherit

  build-esp32-at-all-function-test-just-bt:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROVER-32
      artifacts_name: esp32-at-all-function-test-just-bt
    secrets: inherit

  build-esp32c3-mini-1-at:
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: MINI-1
      artifacts_name: esp32c3-mini-1-at
    secrets: inherit

  build-esp32c3-spi-at:
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: ESP32C3-SPI
      artifacts_name: esp32c3-spi-at
    secrets: inherit

  build-esp32c3-at-full-function-test:
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: MINI-1
      artifacts_name: esp32c3-at-full-function-test
    secrets: inherit

  build-esp32c3-rainmaker:
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: ESP32C3_RAINMAKER
      artifacts_name: esp32c3-rainmaker-at
    secrets: inherit

  build-esp32c2-4mb-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-4MB
      artifacts_name: esp32c2-4MB-at
    secrets: inherit

  build-esp32c2-2mb-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB
      artifacts_name: esp32c2-2MB-at
    secrets: inherit

  build-esp32c2-2mb-ble-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB-BLE
      artifacts_name: esp32c2-2mb-ble-at
    secrets: inherit

  build-esp32c5-4mb-at:
    uses: ./.github/workflows/build_template_esp32c5.yml
    with:
      module_name: ESP32C5-4MB
      artifacts_name: esp32c5-4MB-at
    secrets: inherit

  build-esp32c2-4mb-g2-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-4MB-G2
      artifacts_name: esp32c2-4MB-g2-at
    secrets: inherit

  build-esp32c2-2mb-g2-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB-G2
      artifacts_name: esp32c2-2MB-g2-at
    secrets: inherit

  build-esp32c2-2mb-ble-g2-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB-BLE-G2
      artifacts_name: esp32c2-2mb-ble-g2-at
    secrets: inherit

  build-esp32c2-2mb-no-ota-g2-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB-NO-OTA-G2
      artifacts_name: esp32c2-2mb-no-ota-g2-at
    secrets: inherit

  build-esp32c6-4mb-at:
    uses: ./.github/workflows/build_template_esp32c6.yml
    with:
      module_name: ESP32C6-4MB
      artifacts_name: esp32c6-4MB-at
    secrets: inherit

  build-esp32s2-mini-at:
    uses: ./.github/workflows/build_template_esp32s2.yml
    with:
      module_name: MINI
      artifacts_name: esp32s2-mini-at
    secrets: inherit

  build-esp32c2-4mb-ble-g2-at:
    steps:
      - run: echo -e "CONFIG_AT_BLE_COMMAND_SUPPORT=y" >> module_config/module_esp32c2-4mb-g2/sdkconfig.defaults
      - uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-4MB-G2
      artifacts_name: esp32c2-4MB-ble-g2-at
    secrets: inherit